# Generated by Django 3.1.2 on 2020-11-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='higlighted',
            new_name='highlighted',
        ),
    ]
